name: MDBOOK

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/**'

jobs:
  lint-markdown:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Lint markdown format
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          FILTER_REGEX_INCLUDE: .*docs/.*md$
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true

  build-mdbook:
    needs: lint-markdown
    if: |
      always()
      && (needs.lint-markdown.result == 'success' || needs.lint-markdown.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@adeb05db28a0c0004681db83893d56c0388ea9ea # v1.2.0
        with:
          mdbook-version: 'latest'

      - name: Install mdBook preprocessors
        run: |
          cargo install mdbook-variables --locked

      - name: Create work dir
        run: |
          cd docs/book/
          mkdir target

      - name: Build English version
        run: |
          cd docs/book/en
          mdbook build
          cp -r book ../target/en

      - name: Publish EN version
        if: ${{ github.event_name == 'push' }}
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900 # main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_WWW }}
        with:
          source-directory: 'docs/book/target'
          destination-github-username: 'WasmEdge'
          destination-repository-name: 'www'
          target-directory: 'book'
          user-email: michael@secondstate.io
          target-branch: main
