name: Build on Fedora

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      release:
        type: boolean
      upload_asset_url:
        type: string
        
permissions:
  contents: read
  
jobs:
  build_fedora:
    permissions:
      contents: write
    name: Fedora latest
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Install dependency
        run: |
          dnf update -y
          dnf install -y cmake ninja-build llvm llvm-devel lld-devel clang git file rpm-build dpkg-dev spdlog-devel \
            pkgconf-pkg-config protobuf-c-compiler grpc-cpp grpc-plugins grpc-devel
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Grant the safe directory for git
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Build WasmEdge
        run: |
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON -DWASMEDGE_BUILD_PACKAGE="TGZ;DEB;RPM" .
          cmake --build build
      - name: Test WasmEdge
        run: |
          export LD_LIBRARY_PATH="$(pwd)/build/lib/api:$LD_LIBRARY_PATH"
          cd build
          ./tools/wasmedge/wasmedge -v
          ctest
          cd -
      - name: Create package tarball
        run: |
          cmake --build build --target package
      - name: Upload artifact
        if: ${{ !inputs.release }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: WasmEdge-${{ inputs.version }}-fedora35.tar.gz
          path: build/WasmEdge-${{ inputs.version }}-Linux.tar.gz
