name: Build extensions

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      release:
        type: boolean
        default: false

jobs:
  prepare:
    name: Prepare matrix values
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prep.outputs.matrix }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - id: prep
        uses: ./.github/actions/expand-variables

  build_extensions_on_manylinux:
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    name: Build all plugins on ${{ matrix.docker_tag }}
    uses: ./.github/workflows/reusable-build-extensions-on-manylinux.yml
    with:
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}
      docker_tag: ${{ matrix.docker_tag }}
      plugins: ${{ toJSON(matrix.plugins) }}
      version: ${{ inputs.version }}
      release: ${{ inputs.release }}
    secrets: inherit
