name: Clang-Format

on:
  workflow_call:
    
permissions:
  contents: read
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Install clang-format-15
        run: |
          sudo apt update
          sudo apt install clang-format-15
      - name: Run clang-format
        run: |
          bash ./.github/scripts/clang-format.sh `which clang-format-15`
