name: Static Code Analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches:
      - master
    paths:
      - ".github/workflows/static-code-analysis.yml"
      - "include/**"
      - "lib/**"
      - "plugins/**"
      - "test/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"
  pull_request:
    branches:
      - master
      - 'proposal/**'
    paths:
      - ".github/workflows/static-code-analysis.yml"
      - "include/**"
      - "lib/**"
      - "plugins/**"
      - "test/**"
      - "thirdparty/**"
      - "tools/**"
      - "CMakeLists.txt"
      - "cmake/**"

permissions:
  contents: read
  
jobs:
  static_analysis:
    permissions:
      contents: write
    name: Run Static Code Analysis using Infer
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Ensure git safe directory
      run: |
        git config --global --add safe.directory $(pwd)

    - name: Install Dependencies
      run: |
        lsb_release -a
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y software-properties-common llvm-11-dev liblld-11-dev liblld-11 clang-11 tar libssl-dev
        curl -sSL "https://github.com/facebook/infer/releases/download/v1.1.0/infer-linux64-v1.1.0.tar.xz" | sudo tar -C /opt -xJ && sudo ln -s "/opt/infer-linux64-v1.1.0/bin/infer" /usr/local/bin/infer

    - name: Generate compilation database
      run: |
        mkdir build
        cd build
        infer compile -- cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_DIR=/usr/lib/llvm-11/lib/cmake/llvm -DWASMEDGE_PLUGIN_WASI_CRYPTO=ON ..

    - name: Run Infer Static Code Analysis
      run: |
        cd build
        infer run --keep-going -- make -j 4

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: report
        path: |
          build/infer-out/report.txt
          build/infer-out/report.json
